name: NsiProjekat1 App start Tests

on:
  push:
    branches:
      - "feature/*" # matches every feature branch containing a single '/'
      - "main" # matches main branch '/'
      - "!release/**" # excludes release

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Set Test Environment Variable
        run: echo "ASPNETCORE_ENVIRONMENT=Test" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release NsiProjekat1.sln
      - name: Test
        run: dotnet test --configuration Release NsiProjekat1.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
      - name: Login
        run: docker login nsiprojekat.azurecr.io -u ${{secrets.nsi_projekat1_user}} -p ${{secrets.nsi_projekat1_pass}}
      - name: Docker Build and Push
        run: | 
            docker build -f NsiProjekat1.Api/Dockerfile --force-rm -t nsiprojekat.azurecr.io/nsiprojekat:v1 .
            docker push nsiprojekat.azurecr.io/nsiprojekat:v1
      - name: Dotnet tool install
        run: | 
            dotnet tool install --global dotnet-ef
            dotnet tool restore
      - name: Add migration
        run: dotnet ef migrations add NewMigration --verbose --project NsiKlk1.Infrastructure --startup-project NsiKlk1.Api
      - name: Database update
        run: dotnet ef database update --verbose --project NsiKlk1.Infrastructure --startup-project NsiKlk1.Api